### ISSUE TITLE
Bad Error Messages

### ISSUE THREAD

**Issue by BenDol** [ArcBees/GWTP#553]
I am really wanting to find a solution to this, but nothing I have found so far is helpful (even compiling doesn't help). I receive an error message sometimes while developing, might be that I have accidently included code that isn't available or a failure on starting for whatever reason:

```
[DEBUG] [ims] - Rebinding com.gwtplatform.mvp.client.ApplicationController
	[DEBUG] [ims] - Invoking generator com.gwtplatform.mvp.rebind.ApplicationControllerGenerator
		[ERROR] [ims] - The type 'nz.co.doltech.ims.client.BootstrapperImpl.PreBootstrapperImpl' was not found.
[ERROR] [ims] - Deferred binding failed for 'com.gwtplatform.mvp.client.ApplicationController'; expect subsequent failures
[ERROR] [ims] - Unable to load module entry point class nz.co.doltech.ims.client.Application (see associated exception for details)
[ERROR] [ims] - Failed to load module 'ims' from user agent 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0' at localhost:4814
```

```
EntryPoint initialization exception

Exception while loading module nz.co.doltech.ims.client.Application. See Development Mode for details.
java.lang.ExceptionInInitializerError at java.lang.Class.forName0(Native Method) 
  at java.lang.Class.forName(Unknown Source) 
  at com.google.gwt.dev.shell.ModuleSpace.loadClassFromSourceName(ModuleSpace.java:665) 
  at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:373)
  at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200) 
  at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:526) 
  at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:364) 
  at java.lang.Thread.run(Unknown Source) Caused by: java.lang.RuntimeException: Deferred binding failed for 'com.gwtplatform.mvp.client.ApplicationController' (did you forget to inherit a required module?) 
  at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:53)
  at com.google.gwt.core.shared.GWT.create(GWT.java:57) 
  at nz.co.doltech.ims.client.Application.<clinit>(Application.java:12) 
  ... 8 more Caused by: com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries) 
  at com.google.gwt.dev.shell.ModuleSpace.rebind(ModuleSpace.java:605) 
  at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:465) 
  at com.google.gwt.dev.shell.GWTBridgeImpl.create(GWTBridgeImpl.java:49) 
  ... 10 more 
```
This message gives me absolutely no information as to what is going wrong. How can I get the actual issue message, rather than this useless message about the ApplicationController etc?

**EDIT:**
The issue was this (after 30 minutes of removing changes to identify it):
```java
return Integer.compare(o1, o2);
```
So I changed it to this:
```java
return Double.compare(o1, o2);
```
and it worked again. Issue is that GWT doesn't have an Integer.compare method yet I believe. But I mean why couldn't I get that error message instead of the rubbish above? Haha, would have saved me 30 minutes.

**Comment by olafleur** [comment]
Do you still have this error with the newest version of GTWP? Should we close that issue or keep it open?

**Comment by BenDol** [comment]
Yes but it appears to be a limitation with GIN. Its won't tell me where or what the issue is since the  magic somewhat swallows up proper error messages.
