### ISSUE TITLE
GeneratedGwtpModule

### ISSUE THREAD

**Issue by LeshaRB** [ArcBees/GWTP#820]
Hello I try compile application and have error
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Can not create source file `com.gwtplatform.common.client.GeneratedGwtpModule`.
[ERROR] javax.annotation.processing.FilerException: Attempt to reopen a file for path D:\Work\admin\target\classes\com\gwtplatform\common\client\GeneratedGwtpModule.java
  	at com.sun.tools.javac.processing.JavacFiler.checkFileReopening(JavacFiler.java:535)
  	at com.sun.tools.javac.processing.JavacFiler.createResource(JavacFiler.java:431)
  	at com.gwtplatform.processors.tools.outputter.GwtFileObject.<init>(GwtFileObject.java:92)
  	at com.gwtplatform.processors.tools.outputter.OutputType$2.createFileObject(OutputType.java:38)
  	at com.gwtplatform.processors.tools.outputter.Outputter.prepareSourceFile(Outputter.java:129)
  	at com.gwtplatform.processors.tools.outputter.Outputter.prepareSourceFile(Outputter.java:124)
  	at com.gwtplatform.processors.tools.bindings.gin.GinModuleProcessor.ensureSourceFileIsCreated(GinModuleProcessor.java:76)
  	at com.gwtplatform.processors.tools.bindings.gin.GinModuleProcessor.process(GinModuleProcessor.java:55)
  	at com.gwtplatform.processors.tools.bindings.gin.GinModuleProcessor.process(GinModuleProcessor.java:37)
  	at com.gwtplatform.processors.tools.bindings.BindingsProcessors.process(BindingsProcessors.java:55)
  	at com.gwtplatform.mvp.processors.DefaultGatekeeperProcessor.createBinding(DefaultGatekeeperProcessor.java:162)
  	at com.gwtplatform.mvp.processors.DefaultGatekeeperProcessor.processAsApp(DefaultGatekeeperProcessor.java:82)
  	at com.gwtplatform.common.processors.AbstractGwtpAppProcessor.processSafe(AbstractGwtpAppProcessor.java:45)
  	at com.gwtplatform.processors.tools.AbstractProcessor.process(AbstractProcessor.java:111)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
  	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.665 s
[INFO] Finished at: 2017-01-27T16:51:00+03:00
[INFO] Final Memory: 35M/280M
```

**Comment by LeshaRB** [comment]
Don't work
```
            <dependency>
                <groupId>com.gwtplatform</groupId>
                <artifactId>gwtp-all</artifactId>
                <version>${gwtp.version}</version>
                <scope>provided</scope>
            </dependency>

```
But when I change on this dependcies all work fine

```
            <dependency>
                <groupId>com.gwtplatform</groupId>
                <artifactId>gwtp-mvp-client</artifactId>
                <version>${gwtp.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>com.gwtplatform</groupId>
                <artifactId>gwtp-dispatch-rpc-client</artifactId>
                <version>${gwtp.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>com.gwtplatform</groupId>
                <artifactId>gwtp-dispatch-rpc-server-guice</artifactId>
                <version>${gwtp.version}</version>
                <scope>provided</scope>
            </dependency>
```

**Comment by meriouma** [comment]
Which version of GWTP are you using?

**Comment by LeshaRB** [comment]
Hello 2.0-SnapShot
